#!/bin/sh
# Copyright (C) 2015-2022 Greenbone AG
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Escalator method script: Send.

header='{"alg": "HS256", "typ": "JWT"}'
payload='{"sub": "", "username": "", "tenant": ""}'
secret_key=$SECRET_JWT_KEY
url="${API_SERVICE_URL}/api/v1.0/report/external-vulnerability-report"

encoded_header=$(echo -n "$header" | base64 | tr -d '\n=' | tr '/+' '_-')
encoded_payload=$(echo -n "$payload" | base64 | tr -d '\n=' | tr '/+' '_-')
signature=$(echo -n "$encoded_header.$encoded_payload" | openssl dgst -binary -sha256 -hmac $secret_key | base64 | tr -d '\n=' | tr '/+' '_-')
jwt="$encoded_header.$encoded_payload.$signature"

report_content=$(cat $3)
report=$(echo "$report_content" | sed "s/\"/'/g")

request_body="{\"xml\": \"${report}\"}"

curl --location --retry 5 --retry-max-time 60 -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $jwt" -d "$request_body" "$url"

EXIT_CODE=$?
exit $EXIT_CODE
